version: "3"

services:
  service_setup:
    image: "app-base"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: j7s25k23m
      POSTGRES_DB: cars_recognition
      POSTGRES_HOST: localhost
      # POSTGRES_PORT: 5432
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: "nvidia"
    #           device_ids: ["0"]
    #           capabilities: [gpu]
    build:
      context: .
      dockerfile: Dockerfile

  service_statr:
    image: "app-base"
    command: "start"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: j7s25k23m
      POSTGRES_DB: cars_recognition
      POSTGRES_HOST: localhost
      # POSTGRES_PORT: 5432
    # volumes:
    #   - /dev/video0: /dev/video0
    # devices:
    #   - /dev/video0:/dev/video0
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: "nvidia"
    #           device_ids: ["0"]
    #           capabilities: [gpu]
    restart: unless-stopped
    network_mode: "host"
